endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
    
zuul:
  prefix: /services
  routes:
    card:
      path: /card/**
      service-id: card
      retryable: true
    config:
      path: /config/**
      service-id: config
      retryable: true

ribbon:
  eureka:
    enabled: true

server:
  port: 8765
  
eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 1
    instance-info-replication-interval-seconds: 2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2